"""add_despesa_breakdown_and_quality_sync_state

Revision ID: 043c91035847
Revises: 7b6610d4f1c2
Create Date: 2026-04-25 12:51:38.041971

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "043c91035847"
down_revision: str | None = "7b6610d4f1c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despesa_breakdown',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('breakdown_type', sa.String(length=30), nullable=False),
    sa.Column('item_label', sa.String(length=500), nullable=False),
    sa.Column('valor', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fonte', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano', 'mes', 'breakdown_type', 'item_label', name='uq_despesa_breakdown_identity')
    )
    op.create_index(op.f('ix_despesa_breakdown_ano'), 'despesa_breakdown', ['ano'], unique=False)
    op.create_index(op.f('ix_despesa_breakdown_breakdown_type'), 'despesa_breakdown', ['breakdown_type'], unique=False)
    op.create_index(op.f('ix_despesa_breakdown_mes'), 'despesa_breakdown', ['mes'], unique=False)
    op.create_index('ix_despesa_breakdown_type_ano', 'despesa_breakdown', ['breakdown_type', 'ano'], unique=False)
    op.create_index('ix_despesa_breakdown_type_ano_mes', 'despesa_breakdown', ['breakdown_type', 'ano', 'mes'], unique=False)
    op.create_table('quality_sync_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_key', sa.String(length=80), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=False),
    sa.Column('last_changed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_key', 'ano', name='uq_quality_sync_state_dataset_ano')
    )
    op.create_index('ix_quality_sync_state_checked', 'quality_sync_state', ['last_checked_at'], unique=False)
    op.create_table('quality_unidade_gestora',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_entidade', sa.Integer(), nullable=False),
    sa.Column('nome_entidade', sa.String(length=255), nullable=False),
    sa.Column('tipo_entidade', sa.Integer(), nullable=True),
    sa.Column('cnpj_entidade', sa.String(length=20), nullable=True),
    sa.Column('tipo_unidade_gestora', sa.Integer(), nullable=True),
    sa.Column('fonte', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_entidade', name='uq_quality_unidade_gestora_codigo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quality_unidade_gestora')
    op.drop_index('ix_quality_sync_state_checked', table_name='quality_sync_state')
    op.drop_table('quality_sync_state')
    op.drop_index('ix_despesa_breakdown_type_ano_mes', table_name='despesa_breakdown')
    op.drop_index('ix_despesa_breakdown_type_ano', table_name='despesa_breakdown')
    op.drop_index(op.f('ix_despesa_breakdown_mes'), table_name='despesa_breakdown')
    op.drop_index(op.f('ix_despesa_breakdown_breakdown_type'), table_name='despesa_breakdown')
    op.drop_index(op.f('ix_despesa_breakdown_ano'), table_name='despesa_breakdown')
    op.drop_table('despesa_breakdown')
    # ### end Alembic commands ###
