"""add_convenios_table

Revision ID: 5e79bec64e46
Revises: 5ed4359a4e35
Create Date: 2026-05-17 10:39:29.838473

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e79bec64e46"
down_revision: str | None = "5ed4359a4e35"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "convenio_movimentacoes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("mes", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("convenio", sa.String(length=50), nullable=False),
        sa.Column("lancamento", sa.String(length=200), nullable=True),
        sa.Column("entidade", sa.String(length=500), nullable=True),
        sa.Column("data", sa.String(length=20), nullable=True),
        sa.Column("concedente", sa.String(length=500), nullable=True),
        sa.Column("convenente", sa.String(length=500), nullable=True),
        sa.Column("valor", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("fonte", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ano",
            "mes",
            "tipo",
            "convenio",
            "lancamento",
            name="uq_convenio_mov_identity",
        ),
    )
    op.create_index(
        "ix_convenio_mov_ano_mes",
        "convenio_movimentacoes",
        ["ano", "mes"],
        unique=False,
    )
    op.create_index(
        "ix_convenio_mov_tipo_ano",
        "convenio_movimentacoes",
        ["tipo", "ano"],
        unique=False,
    )
    op.create_table(
        "convenios",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ano", sa.Integer(), nullable=False),
        sa.Column("numero", sa.String(length=50), nullable=False),
        sa.Column("assinatura", sa.String(length=20), nullable=True),
        sa.Column("tipo", sa.String(length=50), nullable=False),
        sa.Column("esfera", sa.String(length=50), nullable=False),
        sa.Column("concedente", sa.String(length=500), nullable=False),
        sa.Column("convenente", sa.String(length=500), nullable=False),
        sa.Column("valor", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("situacao", sa.String(length=100), nullable=True),
        sa.Column("objeto", sa.Text(), nullable=True),
        sa.Column("fonte", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ano", "numero", name="uq_convenio_ano_numero"),
    )
    op.create_index("ix_convenio_ano", "convenios", ["ano"], unique=False)
    op.create_index(
        "ix_convenio_tipo_ano", "convenios", ["tipo", "ano"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_convenio_tipo_ano", table_name="convenios")
    op.drop_index("ix_convenio_ano", table_name="convenios")
    op.drop_table("convenios")
    op.drop_index("ix_convenio_mov_tipo_ano", table_name="convenio_movimentacoes")
    op.drop_index("ix_convenio_mov_ano_mes", table_name="convenio_movimentacoes")
    op.drop_table("convenio_movimentacoes")
    # ### end Alembic commands ###
