"""add_movimento_extra_table

Revision ID: 90378bdd1b01
Revises: 1c2d3e4f5a6b
Create Date: 2026-05-01 11:20:41.121885

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '90378bdd1b01'
down_revision: str | None = '1c2d3e4f5a6b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimento_extra',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('ent_codigo', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('fornecedor', sa.String(length=500), nullable=False),
    sa.Column('tipo', sa.String(length=1), nullable=False),
    sa.Column('valor_recebido', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fonte', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano', 'mes', 'tipo', 'codigo', 'ent_codigo', name='uq_movimento_extra_identity')
    )
    op.create_index(op.f('ix_movimento_extra_ano'), 'movimento_extra', ['ano'], unique=False)
    op.create_index('ix_movimento_extra_ano_mes', 'movimento_extra', ['ano', 'mes'], unique=False)
    op.create_index('ix_movimento_extra_ano_mes_tipo', 'movimento_extra', ['ano', 'mes', 'tipo'], unique=False)
    op.create_index(op.f('ix_movimento_extra_mes'), 'movimento_extra', ['mes'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimento_extra_mes'), table_name='movimento_extra')
    op.drop_index('ix_movimento_extra_ano_mes_tipo', table_name='movimento_extra')
    op.drop_index('ix_movimento_extra_ano_mes', table_name='movimento_extra')
    op.drop_index(op.f('ix_movimento_extra_ano'), table_name='movimento_extra')
    op.drop_table('movimento_extra')
    # ### end Alembic commands ###
