"""initial

Revision ID: f9d741c1a962
Revises:
Create Date: 2026-04-23 00:05:22.897941

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9d741c1a962"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despesas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=500), nullable=True),
    sa.Column('subcategoria', sa.String(length=500), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valor_empenhado', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_liquidado', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fonte', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_despesa_ano_mes', 'despesas', ['ano', 'mes'], unique=False)
    op.create_index('ix_despesa_categoria_ano', 'despesas', ['categoria', 'ano'], unique=False)
    op.create_index('ix_despesa_tipo_periodo', 'despesas', ['tipo', 'ano', 'mes'], unique=False)
    op.create_index(op.f('ix_despesas_ano'), 'despesas', ['ano'], unique=False)
    op.create_index(op.f('ix_despesas_categoria'), 'despesas', ['categoria'], unique=False)
    op.create_index(op.f('ix_despesas_mes'), 'despesas', ['mes'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('categoria', sa.String(length=500), nullable=True),
    sa.Column('data_prevista', sa.Date(), nullable=False),
    sa.Column('yhat', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('yhat_lower', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('yhat_upper', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo', 'categoria', 'data_prevista', name='uq_forecast_unique')
    )
    op.create_index('ix_forecast_tipo_data', 'forecasts', ['tipo', 'data_prevista'], unique=False)
    op.create_index(op.f('ix_forecasts_categoria'), 'forecasts', ['categoria'], unique=False)
    op.create_index(op.f('ix_forecasts_data_prevista'), 'forecasts', ['data_prevista'], unique=False)
    op.create_index(op.f('ix_forecasts_tipo'), 'forecasts', ['tipo'], unique=False)
    op.create_table('metadata_etl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('arquivo', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('registros_processados', sa.Integer(), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_etl_arquivo', 'metadata_etl', ['arquivo'], unique=False)
    op.create_index('ix_etl_tipo_ano', 'metadata_etl', ['tipo', 'ano'], unique=False)
    op.create_table('obras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hash', sa.String(length=32), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('secretaria', sa.String(length=255), nullable=False),
    sa.Column('orgao', sa.String(length=255), nullable=False),
    sa.Column('contrato', sa.String(length=255), nullable=False),
    sa.Column('tipo_obra', sa.String(length=255), nullable=False),
    sa.Column('modalidade', sa.String(length=255), nullable=False),
    sa.Column('fonte_recurso', sa.String(length=255), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('previsao_termino', sa.Date(), nullable=True),
    sa.Column('data_termino', sa.Date(), nullable=True),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('bairro', sa.String(length=255), nullable=False),
    sa.Column('cep', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('valor_orcamento', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valor_original', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valor_aditivo', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valor_homologado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valor_contrapartida', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valor_convenio', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('progresso_fisico', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('progresso_financeiro', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obras_hash'), 'obras', ['hash'], unique=True)
    op.create_index(op.f('ix_obras_status'), 'obras', ['status'], unique=False)
    op.create_table('receita_detalhamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('detalhamento', sa.String(length=500), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valor_previsto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_arrecadado', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_anulado', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fonte', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano', 'detalhamento', 'ordem', name='uq_detalhamento_ano_cat_ordem')
    )
    op.create_index('ix_detalhamento_ano_nivel', 'receita_detalhamento', ['ano', 'nivel'], unique=False)
    op.create_index('ix_detalhamento_ano_ordem', 'receita_detalhamento', ['ano', 'ordem'], unique=False)
    op.create_index(op.f('ix_receita_detalhamento_ano'), 'receita_detalhamento', ['ano'], unique=False)
    op.create_table('receitas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=500), nullable=False),
    sa.Column('subcategoria', sa.String(length=500), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valor_previsto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_arrecadado', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('valor_anulado', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fonte', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano', 'mes', 'categoria', name='uq_receita_periodo_categoria')
    )
    op.create_index('ix_receita_ano_mes', 'receitas', ['ano', 'mes'], unique=False)
    op.create_index('ix_receita_categoria_ano', 'receitas', ['categoria', 'ano'], unique=False)
    op.create_index(op.f('ix_receitas_ano'), 'receitas', ['ano'], unique=False)
    op.create_index(op.f('ix_receitas_categoria'), 'receitas', ['categoria'], unique=False)
    op.create_index(op.f('ix_receitas_mes'), 'receitas', ['mes'], unique=False)
    op.create_table('scraping_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraping_log_data_type'), 'scraping_log', ['data_type'], unique=False)
    op.create_index('ix_scraping_log_started', 'scraping_log', ['started_at'], unique=False)
    op.create_index('ix_scraping_log_type_year', 'scraping_log', ['data_type', 'year'], unique=False)
    op.create_index(op.f('ix_scraping_log_year'), 'scraping_log', ['year'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('identity_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_type', sa.String(length=32), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_identity_tokens_exp', 'identity_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_identity_tokens_jti'), 'identity_tokens', ['jti'], unique=True)
    op.create_index('ix_identity_tokens_user_type', 'identity_tokens', ['user_id', 'token_type'], unique=False)
    op.create_table('obra_medicoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('sequencia', sa.Integer(), nullable=False),
    sa.Column('mes_referencia', sa.Integer(), nullable=False),
    sa.Column('ano_referencia', sa.Integer(), nullable=False),
    sa.Column('valor_medicao', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('obra_id', 'sequencia', name='uq_obra_medicao_sequencia')
    )
    op.create_index('ix_obra_medicoes_periodo', 'obra_medicoes', ['ano_referencia', 'mes_referencia'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_obra_medicoes_periodo', table_name='obra_medicoes')
    op.drop_table('obra_medicoes')
    op.drop_index('ix_identity_tokens_user_type', table_name='identity_tokens')
    op.drop_index(op.f('ix_identity_tokens_jti'), table_name='identity_tokens')
    op.drop_index('ix_identity_tokens_exp', table_name='identity_tokens')
    op.drop_table('identity_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scraping_log_year'), table_name='scraping_log')
    op.drop_index('ix_scraping_log_type_year', table_name='scraping_log')
    op.drop_index('ix_scraping_log_started', table_name='scraping_log')
    op.drop_index(op.f('ix_scraping_log_data_type'), table_name='scraping_log')
    op.drop_table('scraping_log')
    op.drop_index(op.f('ix_receitas_mes'), table_name='receitas')
    op.drop_index(op.f('ix_receitas_categoria'), table_name='receitas')
    op.drop_index(op.f('ix_receitas_ano'), table_name='receitas')
    op.drop_index('ix_receita_categoria_ano', table_name='receitas')
    op.drop_index('ix_receita_ano_mes', table_name='receitas')
    op.drop_table('receitas')
    op.drop_index(op.f('ix_receita_detalhamento_ano'), table_name='receita_detalhamento')
    op.drop_index('ix_detalhamento_ano_ordem', table_name='receita_detalhamento')
    op.drop_index('ix_detalhamento_ano_nivel', table_name='receita_detalhamento')
    op.drop_table('receita_detalhamento')
    op.drop_index(op.f('ix_obras_status'), table_name='obras')
    op.drop_index(op.f('ix_obras_hash'), table_name='obras')
    op.drop_table('obras')
    op.drop_index('ix_etl_tipo_ano', table_name='metadata_etl')
    op.drop_index('ix_etl_arquivo', table_name='metadata_etl')
    op.drop_table('metadata_etl')
    op.drop_index(op.f('ix_forecasts_tipo'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_data_prevista'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_categoria'), table_name='forecasts')
    op.drop_index('ix_forecast_tipo_data', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_despesas_mes'), table_name='despesas')
    op.drop_index(op.f('ix_despesas_categoria'), table_name='despesas')
    op.drop_index(op.f('ix_despesas_ano'), table_name='despesas')
    op.drop_index('ix_despesa_tipo_periodo', table_name='despesas')
    op.drop_index('ix_despesa_categoria_ano', table_name='despesas')
    op.drop_index('ix_despesa_ano_mes', table_name='despesas')
    op.drop_table('despesas')
    # ### end Alembic commands ###
